### ISSUE TITLE
弹窗有 X 也有 cancel

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/honzon-platform#10]
<img width="340" alt="Screen Shot 2020-02-18 at 4 55 19 PM" src="https://user-images.githubusercontent.com/1201310/74702641-73733900-526f-11ea-9a71-d1510e74f788.png">

X 和 cancel 都是关掉，可以把cancel去掉，cancel 本身也没有首字母大写

**Comment by qwer951123** [comment]
去除 x 按钮
