### ISSUE TITLE
查询节点运行状态界面优化建议

### ISSUE THREAD

**Issue by lyhycc** [AcalaNetwork/honzon-platform#105]
在下面的查询节点运行状态的的界面的几点优化建议
https://telemetry.polkadot.io/#list/Acala%20Mandala%20TC3
1、就像鱼池等矿池一样可以通过节点的地址进行查询过滤节点；
2、可以点击节点列表进入节点运行状态曲线，包括节点区块时间、带宽等；
3、另外我发现这个界面性能比较慢，应该是刷新频率和刷新方式不是很合理，监控数据的刷新采用AJAX的方式，不要进行全页刷新；
4、另外刷新频率不需要这么高。自动刷新可以几分钟刷新一次，然后允许进行手工刷新。
5HVfcWDci33Ekkg626Mh7QjEaoRZRBByxnLo4R2Uss6z7Woj

**Comment by qwer951123** [comment]
Thanks for your feedback, if you have some suggestions, please move to [substrate-telemetry](https://github.com/paritytech/substrate-telemetry)
