### ISSUE TITLE
Self Serviced Loan page UI BUG

### ISSUE THREAD

**Issue by atinst** [AcalaNetwork/honzon-platform#106]

**Comment by qwer951123** [comment]
Thanks for your feedback, we are now adjusting the website for the small screen.

**Comment by atinst** [comment]
![Snipaste_2020-05-18_14-00-51](https://user-images.githubusercontent.com/32417799/82179372-c6ad6400-9910-11ea-8a6b-5d9d824946f6.png)

**Comment by atinst** [comment]
![Snipaste_2020-05-18_14-06-07](https://user-images.githubusercontent.com/32417799/82179621-5d7a2080-9911-11ea-99f9-25d49224d363.png)

**Comment by atinst** [comment]
> Thanks for your feedback, we are now adjusting the website for the small screen.
So what I'm saying is that bugs don't get rewards?

**Comment by atinst** [comment]
> Thanks for your feedback, we are now adjusting the website for the small screen.

So what I'm saying is that bugs don't get rewards?

**Comment by atinst** [comment]
@qwer951123
