### ISSUE TITLE
Exchange needs to show the account balance

### ISSUE THREAD

**Issue by jiangfuyao** [AcalaNetwork/honzon-platform#14]
Exchange page needs to show the account balance.

example, just for demo, not UI:

![屏幕快照 2020-02-28 下午1 45 51](https://user-images.githubusercontent.com/34789555/75513947-407c3280-5a31-11ea-99fd-39797ab4b6a7.png)

or:

![屏幕快照 2020-02-28 下午1 53 50](https://user-images.githubusercontent.com/34789555/75514178-cc8e5a00-5a31-11ea-83f3-b3425099628a.png)

or:  

![屏幕快照 2020-02-2q18 下午1 45 51](https://user-images.githubusercontent.com/34789555/75513980-512ca880-5a31-11ea-8944-7166f2cf22e7.png)

**Comment by qwer951123** [comment]
move to #21
