### ISSUE TITLE
生成ausd时，未签名交易 却有一条交易记录 [BUG]

### ISSUE THREAD

**Issue by polkadot-code** [AcalaNetwork/honzon-platform#18]
谷歌浏览器

操作流程：
ttps://apps.acala.network/#/loan
self serviced loan -> 点击generate -> polkadot-ex -> cancel

发现交易列表多了一条交易记录
https://polkascan.io/pre/acala-mandala/extrinsic/0x5ba37bdedf038bf6595e1148cf323be05b7e4c19a3aaf011cfbf1e626846bbd2

很难知道是否已经生成成功

5FLcXWfs1hpRqbT4Rv5ACHkenqCGL5MPTDDeFtBFrogY3D9V

**Comment by qwer951123** [comment]
历史记录里面目前会显示交易失败和取消的记录用于调试，我们将会在下个版本更新中修改交易记录组价

**Comment by qwer951123** [comment]
completed at #62
