### ISSUE TITLE
没有波卡插件的账户名 每次操作要核对几遍

### ISSUE THREAD

**Issue by polkadot-code** [AcalaNetwork/honzon-platform#19]
![image](https://user-images.githubusercontent.com/61858805/76051551-24830e80-5fa6-11ea-9793-815278440644.png)

会引起误操作 造成不必要损失

5FLcXWfs1hpRqbT4Rv5ACHkenqCGL5MPTDDeFtBFrogY3D9V

**Comment by jiangfuyao** [comment]
@polkadot-code Already rewarded.

**Comment by qwer951123** [comment]
completed at #62
