### ISSUE TITLE
交易记录内容为空

### ISSUE THREAD

**Issue by polkadot-code** [AcalaNetwork/honzon-platform#20]
https://polkascan.io/pre/acala-mandala/extrinsic/0x5fd7e569f777127263a55bc9f923a41db8429fda2089e146f337f5af2994ac62

![image](https://user-images.githubusercontent.com/61858805/76053135-2b5e5100-5fa7-11ea-839a-e59ffb50e0e9.png)

交易真实确认了吗

5FLcXWfs1hpRqbT4Rv5ACHkenqCGL5MPTDDeFtBFrogY3D9V

**Comment by jiangfuyao** [comment]
@polkadot-code Hey, guys. The Polkascan Acala node has been stoped. We will contact him to restart it.
Now this way have the block data: https://console.acala.network/#/explorer

**Comment by polkadot-code** [comment]
> @polkadot-code Hey, guys. The Polkascan Acala node has been stoped. We will contact him to restart it.
> Now this way have the block data: https://console.acala.network/#/explorer

subscan好用点

**Comment by qwer951123** [comment]
0x5fd7e569f777127263a55bc9f923a41db8429fda2089e146f337f5af2994ac62 packed in block#60342, you can use https://console.acala.network/#/explorer to  confirm.
