### ISSUE TITLE
exchange中交易失败

### ISSUE THREAD

**Issue by olddaddy2020** [AcalaNetwork/honzon-platform#22]
谷歌浏览器
http://apps.acala.network/#/exchange
用ausd与xbtc进行exchange时，在输入密码后会卡顿，然后大部分情况下会交易失败，而且Tx Hash一闪就消失了，无法查看是何原因造成失败

5GR5ZkscxFJHRroPDPG6TxZ28xGJBnsrYXJCR9nbmiuWWEDR

**Comment by qwer951123** [comment]
在 exchange 中交换的资产，可能会失败。假设你的交易的同时其他人也发起了交易，并且其他人的交易先与你的交易被打包，流通池中的资产已经被其他人拿走，从而导致了交易失败

**Comment by qwer951123** [comment]
we have already added some methods to avoid most failed, thanks for your support.
