### ISSUE TITLE
Exchange缺交易历史记录

### ISSUE THREAD

**Issue by olddaddy2020** [AcalaNetwork/honzon-platform#24]
谷歌浏览器

操作流程：
http://apps.acala.network/#/exchange

在进入Exchange时，页面交易对缺少相应交易历史记录展示，建议在页面下半部分添加

5GR5ZkscxFJHRroPDPG6TxZ28xGJBnsrYXJCR9nbmiuWWEDR

**Comment by qwer951123** [comment]
我们在重新设计 exchange 页面，历史记录功能以后会添加上去。
