### ISSUE TITLE
Withdraw collateral failed 

### ISSUE THREAD

**Issue by RomeroYang** [AcalaNetwork/honzon-platform#27]
Tx is pending more than 10 minutes after it was signed and sent:

![image](https://user-images.githubusercontent.com/10572804/76090022-c54cea80-5ff5-11ea-8137-2c75e07c18f8.png)

**Comment by qwer951123** [comment]
可能是网络问题，没有收到交易成功/失败的消息，导致页面一直锁住，由于 tx hash 是在交易成功后读取的，所以没有读取到 tx hash。这个问题我们将会尽快解决。

**Comment by qwer951123** [comment]
completed at #62
