### ISSUE TITLE
Tx Failed Collections 交易失败收集

### ISSUE THREAD

**Issue by qwer951123** [AcalaNetwork/honzon-platform#29]
If you have some tx failed, please commit your account address and tx hash (if have) here.

Some tx failed reasons:
- bad network.
- a lack of assets in the exchange pool.

you could reflash the website to resolve some errors. We will take some precautions to improve the user experience soon.

如果你有一些交易失败，请提交你的账号地址和交易 hash（如果有）到这里。

一些交易失败可能是由于：
- 网络缓慢。
- Exchange 流通池中缺少相应资产。

你可以通过通过简单的刷新页面解决一些问题，我们将会采取一些措施来提醒用户，从而带来更好的用户体验。

**Comment by hijonehi** [comment]
0x1900010000e8890423c78a0000000000000000036a98915edf1104000000000000000000 失败

**Comment by hijonehi** [comment]
0x1900010000e8890423c78a0000000000000000036a98915edf1104000000000000000000 失败
