### ISSUE TITLE
the pool has no enough asset

### ISSUE THREAD

**Issue by hijonehi** [AcalaNetwork/honzon-platform#31]
在exchange中，不管是用dot还是xbtc置换aUSD，都是显示the pool has no enough asset，无法进行交易。

![image](https://user-images.githubusercontent.com/61875854/76159371-bd5a8b00-615a-11ea-9369-e9c02645e631.png)

5G8jj92pf4yG9cQmQ6mbRUqBePMptB37b7GGBg8FMoDKL9Gv

**Comment by qwer951123** [comment]
fixed at #62
