### ISSUE TITLE
Price Feed

### ISSUE THREAD

**Issue by hijonehi** [AcalaNetwork/honzon-platform#32]
XBTC in USD  $9,082.07从昨天到今天好像一直没动过，实际上btc的价格这两天波动很大

![image](https://user-images.githubusercontent.com/61875854/76159861-9f435980-615f-11ea-9d65-191ad32965c3.png)

   

5G8jj92pf4yG9cQmQ6mbRUqBePMptB37b7GGBg8FMoDKL9Gv

**Comment by qwer951123** [comment]
喂价服务昨天停止工作了，已经重启了
