### ISSUE TITLE
Cancelled exchange transaction leads to UI lockup.

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/honzon-platform#33]
1. Submit an exchange, e.g. 99 aUSD for DOT.
2. Cancel the pop up window of confirmation. 
3. Exchange button becomes gray and Swap Currency message keeps circling. The UI is locked and only a refresh will unlock it. Shown as following:

![Xnip2020-03-08_20-07-53](https://user-images.githubusercontent.com/46279370/76162489-3e287f80-6179-11ea-9987-69df146766d1.jpg)

Acala Mandala Account: 5FHCaBgXVmj4iStBArBgPKubNJGRZCjja1j1SfdaKMu5KA2X

**Comment by jiangfuyao** [comment]
@xz-cn Already rewarded.

**Comment by qwer951123** [comment]
completed at #62
