### ISSUE TITLE
Cannot pay back max amount borrowed aUSD

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/honzon-platform#34]
1. Payback aUSD
2. Click on max to payback all. 
3. Type in password in the pop up window and sign the contract.
4. The Window become gray and locks up forever. The transaction was unsuccessful. 

![Xnip2020-03-08_20-45-55](https://user-images.githubusercontent.com/46279370/76163055-f6f0bd80-617d-11ea-95a4-9a7bb2c5d871.jpg)

Acala Mandala Account: 5FHCaBgXVmj4iStBArBgPKubNJGRZCjja1j1SfdaKMu5KA2X

**Comment by qwer951123** [comment]
This will happen when apps don't receive the updatePosition result message, maybe some network problems, we will take some measures to avoid this

**Comment by qwer951123** [comment]
completed at #62
