### ISSUE TITLE
wallet balance

### ISSUE THREAD

**Issue by hijonehi** [AcalaNetwork/honzon-platform#35]
Wallet Balance中，xbtc只显示小数点后两位，太少了，xbtc单价高，大部分钱包和交易所都至少显示5--6位。

![image](https://user-images.githubusercontent.com/61875854/76163338-299bb580-6180-11ea-808d-26d20b038745.png)

5G8jj92pf4yG9cQmQ6mbRUqBePMptB37b7GGBg8FMoDKL9Gv

**Comment by qwer951123** [comment]
嗯，谢谢，我们将会显示5位小数或者更多。

**Comment by jiangfuyao** [comment]
@hijonehi Already rewarded.

**Comment by qwer951123** [comment]
completed at #62
