### ISSUE TITLE
Loan 2 decimal place rounding bug (2 decimal place limit)

### ISSUE THREAD

**Issue by imylomylo** [AcalaNetwork/honzon-platform#37]
Acala Mandala Account: `5F52pY196ZVifs3xGvBK5RTFuWMLsxNPrTfTTfk7NHC4YrS7`

From the loan section, using a value of DOT or XBTC with more then 2 decimal places, rounds to the 2 decimal place.  e.g. 0.017 will round to 0.01

![acala-2dp-rounding-bug](https://user-images.githubusercontent.com/19399102/76293699-6fa06880-62a9-11ea-9778-27146a1df24f.png)
![acala-2dp-rounding-bug-summary](https://user-images.githubusercontent.com/19399102/76293721-75964980-62a9-11ea-82af-d370d60581dd.png)

Minimum value of 0.01 required. Using a DOT or XBTC value less than 0.01 will display a summary of 0.

Impact: Incorrect values in explorers.

**Comment by qwer951123** [comment]
We will keep 5 keep decimals for display.

**Comment by qwer951123** [comment]
completed at #62
