### ISSUE TITLE
Repo build error with babel-eslint

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/honzon-platform#38]
1. Clone repo from github
2. $ yarn install
3. $ yarn run start -> error of module "babel-eslint". Error message is shown below.

![Xnip2020-03-10_16-18-30](https://user-images.githubusercontent.com/46279370/76294166-4efa0200-62ed-11ea-9721-94af3dfbb332.jpg)

Solution:
1. In new repo, delete yarn.lock
2. Remove the line "babel-eslint": "10.x" in package.json
3. Remove the node_modules directory if any.
3. $ yarn install
4. $ yarn start -> success!

Acala Mandala Account: 5FHCaBgXVmj4iStBArBgPKubNJGRZCjja1j1SfdaKMu5KA2X

**Comment by qwer951123** [comment]
refactored the environment and fixed this problem.
