### ISSUE TITLE
Loan can generate more than maximum value (3 decimal places for aUSD values)

### ISSUE THREAD

**Issue by imylomylo** [AcalaNetwork/honzon-platform#40]
Acala Mandala Account: `5F52pY196ZVifs3xGvBK5RTFuWMLsxNPrTfTTfk7NHC4YrS7`

Screen says can generate maximum 66.69 aUSD, but on input, can put values higher than 66.69 (more than 2 decimal places, e.g. 66.695 an extra half a cent based off the current feed&ratio)

![acala-can-generate-6669max](https://user-images.githubusercontent.com/19399102/76296028-7af59300-62ad-11ea-83ce-ac9f362b6682.png)
![acala-can-generate-66695-more-than-max](https://user-images.githubusercontent.com/19399102/76296044-7f21b080-62ad-11ea-8845-9021251d478f.png)

Impact: fractions of a cent above the maximum is inaccurate to the goals of the UI help text, users potentially led to confusion

txhash: https://polkascan.io/pre/acala-mandala/extrinsic/0x637da2a1e16df329103e5c2693bfb96cdf0f4f7f8245fa470d622ce5a6e69432

**Comment by qwer951123** [comment]
the reason is the same as #37 , we will update the decimal place in the next version.
