### ISSUE TITLE
Warning messages when running the honzon platform locally

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/honzon-platform#41]
1. Use of `yarn start` to run the honzon platform. 
2. It takes more than 1 minute to do `Files successfully emitted, waiting for typecheck results...` A bit slow for some reason?
3. When the compile finishes, it give the following warnings. They may not be bugs but I'd paste them just in case you miss anything. 

![Xnip2020-03-11_09-07-59](https://user-images.githubusercontent.com/46279370/76372466-74801d80-6378-11ea-92a4-d67dd924a5f0.jpg)
![Xnip2020-03-11_09-08-11](https://user-images.githubusercontent.com/46279370/76372468-75b14a80-6378-11ea-8472-811edc0ca263.jpg)

Acala Mandala Account: 5FHCaBgXVmj4iStBArBgPKubNJGRZCjja1j1SfdaKMu5KA2X

**Comment by qwer951123** [comment]
Thanks, we will clean the warning message soon or later.
