### ISSUE TITLE
全部赎回XBTC之后OVERVIEW里面XBTC显示Infinity，正常应该是没有才对

### ISSUE THREAD

**Issue by nantianhaike** [AcalaNetwork/honzon-platform#42]
![image](https://user-images.githubusercontent.com/35984173/76823344-e6f86e00-684e-11ea-9348-fa01d5628a41.png)
 Acala Mandala 地址：5ERd1oVWtXy1N9hW2SxHutdsMPDvUkCFvLtMaHYbPXzFrdSn

**Comment by qwer951123** [comment]
Because of your debit value is zero, so the collateral ratio is Infinity, Maybe we should display N/A better.
