### ISSUE TITLE
Exchange section:  "Pay with" edit box should be forbidden unless the number, Possible vulnerability

### ISSUE THREAD

**Issue by mar348** [AcalaNetwork/honzon-platform#44]
My Acala Mandala Account:  5HiYHwLSQme1Tmy3VAJYtkCiCSzPhrhfdnKDzvqZtpP6Npna

We should only allow the input of **numbers** on **Exchange** section, and should not pop up the transaction interface in case of wrong input. This situation is very serious, please fix it.

Following chart:
![acala1](https://user-images.githubusercontent.com/17925290/77184804-4a162900-6b0b-11ea-9d28-61dd7352eb3a.jpg)

**Comment by qwer951123** [comment]
Sure, it will be fixed in the next version.

**Comment by qwer951123** [comment]
fixed at #62
