### ISSUE TITLE
Waste of resources:  transactions about 0 amount when i click the transfer button

### ISSUE THREAD

**Issue by mar348** [AcalaNetwork/honzon-platform#45]
My acala Mandala account: 5HiYHwLSQme1Tmy3VAJYtkCiCSzPhrhfdnKDzvqZtpP6Npna

amount of transaction is zero!
Who can explain the significance of the transfer? Does it need to be improved?

Please check the tx hash:  0x2df2327c954451945b6d2f29e829c47854b9dde6084264046ba35ba363b1ca48

**Comment by qwer951123** [comment]
we will add some checks in this page.
