### ISSUE TITLE
Self Serviced Loan:  Maybe display error about "Max to borrow" for aUSD

### ISSUE THREAD

**Issue by mar348** [AcalaNetwork/honzon-platform#46]
The first input error when i deposit DOT, the prompt 272.72 aUSD about **Max to borrow** is correct. 
![acala3](https://user-images.githubusercontent.com/17925290/77189572-bd6f6900-6b12-11ea-8657-86c812ac515a.jpg)

However, when the second input error occurs, the prompt is not updated in time.  It would mislead us.
![acala4](https://user-images.githubusercontent.com/17925290/77189678-e8f25380-6b12-11ea-9291-3402d87878bf.jpg)

My Acala Mandala Account: 5HiYHwLSQme1Tmy3VAJYtkCiCSzPhrhfdnKDzvqZtpP6Npna

**Comment by qwer951123** [comment]
This input check number format first. ".1" is not a valid number,  so the prompt is correct for me.
