### ISSUE TITLE
The units of ACA currency are inconsistent between acala faucet and acala platform

### ISSUE THREAD

**Issue by mar348** [AcalaNetwork/honzon-platform#47]
My acala Mandala account:  5HiYHwLSQme1Tmy3VAJYtkCiCSzPhrhfdnKDzvqZtpP6Npna

Acala Faucet transfered **2 mACA** when i typed !drip, but my account received **2 ACA** on Acala platform, There must be a problem. Please check it.

**Comment by qwer951123** [comment]
In our chain, Balance has 18 decimals, so '20000000000000000' ACA means 2 ACA in the really world.
Acala Platform helps you do this transformation and then you could see 2 ACA on it.
