### ISSUE TITLE
"Swap Currency" message keeps circling

### ISSUE THREAD

**Issue by randlmac** [AcalaNetwork/honzon-platform#48]
1.Made an exchange
2.The exchange occurred correctly
3."Swap Currency" message keeps circling although I have already moved to the tab "Self Servised Loan" 
4.Only refreshing the page fixes it
![BUG](https://user-images.githubusercontent.com/55245481/77219963-d8120400-6b4b-11ea-9063-ebecea5c9098.png)
Acala Mandala Account   5DCdUUZSEsdB3JBwdyQsKjEwdjWLyVajJaeki66M5YhGYWyK

**Comment by qwer951123** [comment]
Because of some weird reason, the DApp can't receive TX inBlock message, we will fix it in the next version.
