### ISSUE TITLE
转账操作Bug

### ISSUE THREAD

**Issue by zy4l1** [AcalaNetwork/honzon-platform#49]
在这个转账页面中执行一次任意币种的转账操作,要再次进行一次转账操作时,这时候Transfer按钮是点不动的,也就是说一次只能转一次账,下一次转账操作需要重新刷新页面重新选择钱包才可以点动按钮,正常执行操作
![image](https://user-images.githubusercontent.com/62460007/77221369-19bea100-6b84-11ea-97ab-1a78c2309662.png)

5GBM5hNhzHerACkb5aFvK1X4T4CMmBSAVxSGmtsLFp7iPtky

**Comment by qwer951123** [comment]
fixed at #62
