### ISSUE TITLE
Create Loan 按钮

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/honzon-platform#5]
<img width="798" alt="Screen Shot 2020-02-18 at 4 38 09 PM" src="https://user-images.githubusercontent.com/1201310/74701853-0d85b200-526d-11ea-8844-7083f818b00e.png">
 
点一下进入借贷页面，然后这个按钮需要变化状态，或者消失，或者变成一个返回主页的 Cancel

不然的话在之后的步骤中，这个按钮是没有用的，但还是一个 Create Loan

**Comment by qwer951123** [comment]
已修改为隐藏
