### ISSUE TITLE
Transfer提示用语不正确

### ISSUE THREAD

**Issue by hijonehi** [AcalaNetwork/honzon-platform#50]
进入transfer界面，提示用语错误，第一行应该提示Address，而不是amount，目前这两行显示的都是amount。

![image](https://user-images.githubusercontent.com/61875854/77227655-c3ba1f80-6bbc-11ea-9345-15f0fa407561.png)

5G8jj92pf4yG9cQmQ6mbRUqBePMptB37b7GGBg8FMoDKL9Gv

**Comment by jiangfuyao** [comment]
@hijonehi `Account` = `Address`. 意思是`账户`

**Comment by hijonehi** [comment]
> @hijonehi `Account` = `Address`. 意思是`账户`

明白了，看错了
