### ISSUE TITLE
Exchange and Wallet Balance have different Price Feed

### ISSUE THREAD

**Issue by Vcryptor** [AcalaNetwork/honzon-platform#51]
I have 3.77 BTC in my wallet, the current BTC price is 6231$, so 3.77 BTC = 23466$

<img width="633" alt="acala" src="https://user-images.githubusercontent.com/62481941/77234608-7b98fe00-6bb8-11ea-8070-d03f748165c8.png">

But when I want to exchange 3.77 BTC for aUSD I see a totally different price 17409$

<img width="631" alt="acala2" src="https://user-images.githubusercontent.com/62481941/77234659-df232b80-6bb8-11ea-920a-7a0e99bb1a6a.png">

I've created a Loan with 3.77 BTC to borrow 20372 aUSD. Now I want to buy some BTC with aUSD to sell it after the price goes up significantly to pay out my Loan.

<img width="620" alt="acala3" src="https://user-images.githubusercontent.com/62481941/77235080-8acd7b00-6bbb-11ea-9ae0-570049020246.png">

But the amount of BTC that I can buy with borrowed aUSD is very small because the Price of BTC is much higher than it really is. 

<img width="628" alt="acala4" src="https://user-images.githubusercontent.com/62481941/77235262-f7954500-6bbc-11ea-8967-eedb777fabc5.png">

Impact: This price difference may cause people to stop using the platform.

Acala Address: 5GWj7uVdbEhTad1SwTyqaD2W7h1jX3fMSaWweHR3M3KHj9Qs

**Comment by xz-cn** [comment]
I think the price of XBTC is not fixed in the exchange. The price actually fluctuates depending on the supply in the aUSD pool.

**Comment by xlc** [comment]
This is expected.

We have two price sources, the DEX itself, and oracle and the value between them can be different.

We are redesigning the UI to make this clear.
