### ISSUE TITLE
About fee On Exchange section

### ISSUE THREAD

**Issue by mar348** [AcalaNetwork/honzon-platform#52]
swap DOT to aUSD:
firstly, acala plaform take fee **0.6%** off when swapping 1 DOT. (298.21363211 aUSD)
![ex1](https://user-images.githubusercontent.com/17925290/77239300-4c17df00-6c14-11ea-8dd1-a03e92fc180d.jpg)

but,  fee **33.2%** taken off when swapping 100 DOT.  (20027.25155732 aUSD)
![ex2](https://user-images.githubusercontent.com/17925290/77239305-5508b080-6c14-11ea-9cb5-93ecf1b61cb7.jpg)

Please let me know the correct fees.

5HiYHwLSQme1Tmy3VAJYtkCiCSzPhrhfdnKDzvqZtpP6Npna

**Comment by xlc** [comment]
This is expected. The fee is 0.3% for aUSD pairs and 0.6% for trades between non-aUSD pairs.

The rest is slippage. Please check uniswap for examples.

We are redesigning the UI to make this clear.
