### ISSUE TITLE
Empty transfer bug?

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/honzon-platform#53]
1. Click on the Transfer button
![Xnip2020-03-22_22-15-25](https://user-images.githubusercontent.com/46279370/77251663-99cf2e80-6c8a-11ea-816e-95dc4d50d14f.jpg)

2. Give no input, just click the Transfer button.
![Xnip2020-03-22_22-16-44](https://user-images.githubusercontent.com/46279370/77251706-d0a54480-6c8a-11ea-8eb5-0cebf2d8b62d.jpg)

3. The Transfer button becomes gray and nothing happens (this is correct). Click on cancel.
![Xnip2020-03-22_22-14-17](https://user-images.githubusercontent.com/46279370/77251747-21b53880-6c8b-11ea-9be3-673b0688a039.jpg)

4. Start a new transfer as in item 1. The Transfer button remains gray and nothing can be done. Only a refresh will unlock the Transfer button.
![Xnip2020-03-22_22-14-17](https://user-images.githubusercontent.com/46279370/77251785-545f3100-6c8b-11ea-8991-54a3e93d9e5b.jpg)

5FHCaBgXVmj4iStBArBgPKubNJGRZCjja1j1SfdaKMu5KA2X

**Comment by qwer951123** [comment]
fixed at #62
