### ISSUE TITLE
Strange behavior during borrow.

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/honzon-platform#54]
1. Collateralize some XBTC. The collateralization ratio is Infinity.
2. Borrow 0.9 aUSD. A failure massage was generated. Maybe the amount is too low?
![Xnip2020-03-22_22-47-16](https://user-images.githubusercontent.com/46279370/77252609-df422a80-6c8f-11ea-85a1-9648cd35a57a.jpg)
3. Borrow 1 aUSD. Success! 
4. Borrow 0.9 aUSD again. Success!

Question: why the borrow in item 2 failed but the borrow in item 4 succeeded?  Both amount was 0.9 aUSD. Same behavior was observed for amount lower than 1 aUSD such as 0.1 or 0.001. 

5FHCaBgXVmj4iStBArBgPKubNJGRZCjja1j1SfdaKMu5KA2X

**Comment by qwer951123** [comment]
We set the minimum debit value to 1 aUSD, so you can't borrow 0.9 aUSD. We will redesign the app so that you can be noticed the minimum debit.

**Comment by qwer951123** [comment]
Because of your debit value is zero, so the collateral ratio is Infinity, Maybe we should display N/A better.
