### ISSUE TITLE
UI Bug(点击条款,却刷新了页面)

### ISSUE THREAD

**Issue by bsbs112** [AcalaNetwork/honzon-platform#55]
点击Term and condition(条款和条件),不会进入具体条款页面,而是相当于直接刷新了页面,重新选择钱包![image](https://user-images.githubusercontent.com/62599317/77421450-d6c03000-6e06-11ea-9384-b1d1b32d8b9a.png)

环境:MacOS10.13.6 Chrome.

5FQpQZcBV33N8bTwjsv1jmrNw8iwwsNEY37fpSXDhaZMi36z

**Comment by qwer951123** [comment]
sorry, we haven't a user agreement yet, so this is a blank link, we will put it when the user agreement is ready.
