### ISSUE TITLE
Exchange section: Empty xBTC and DOT can swap

### ISSUE THREAD

**Issue by mar348** [AcalaNetwork/honzon-platform#56]
1. Click Exchange
2. Click aUSD icon and select xBTC
3. if you input a special character, ex @ , the platform can load the polkadot js extension to swap.
![ui2](https://user-images.githubusercontent.com/17925290/77439347-e305b680-6e21-11ea-99bf-55db9e8fa941.jpg)

![ui1](https://user-images.githubusercontent.com/17925290/77439315-daad7b80-6e21-11ea-9ae6-e13b9f0eaaa4.jpg)
 
5HiYHwLSQme1Tmy3VAJYtkCiCSzPhrhfdnKDzvqZtpP6Npna

**Comment by qwer951123** [comment]
Thank, the input doesn't check user input completedly, we will fix it. this issue is the same as #44 and will be closed.

**Comment by qwer951123** [comment]
https://acala-testnet.subscan.io
