### ISSUE TITLE
Select Collateral 选择抵押品的可点击区域太小

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/honzon-platform#6]
<img width="795" alt="Screen Shot 2020-02-18 at 4 40 59 PM" src="https://user-images.githubusercontent.com/1201310/74702007-87b63680-526d-11ea-9698-965bb9ebfc73.png">

应该整行都可以点击，最好有个 `:hover` 加上 `cursor: pointer` 提示可以点选

**Comment by qwer951123** [comment]
扩大范围至整行选中
