### ISSUE TITLE
Generate aUSD 页面输入验证不合理

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/honzon-platform#7]
<img width="793" alt="Screen Shot 2020-02-18 at 4 42 59 PM" src="https://user-images.githubusercontent.com/1201310/74702088-bcc28900-526d-11ea-9fe8-b37afa607a36.png">

应该允许用户输入任何数字，但是不支持的数字进入错误状态，而不是拦截用户的输入操作
尤其是我可能先输入aUSD，然后在输入XBTC，目前无法支持这个

错误信息可以提示用户最多可以输多少

Next 按钮应该是 disabled 直到用户输入正确金额

**Comment by qwer951123** [comment]
已修改验证规则
