### ISSUE TITLE
swap时，输入框显示的一个问题

### ISSUE THREAD

**Issue by SKYeru** [AcalaNetwork/honzon-platform#97]
当时进行交易时按得过快，输密码时发现那个输入框不对劲
![C`52I7TFYEX1TC83 $1N)YX](https://user-images.githubusercontent.com/25096858/81909366-13d1c300-95fd-11ea-977d-1cf84ff0551d.png)

5GRbkRH3hi1vbuNd7s3eW9u2YRfhMtDJVVCe3a8M1jvhBuvZ

**Comment by qwer951123** [comment]
Thanks for the feedback, but I can't reproduce this bug.
